### ISSUE TITLE
Add RowListProxy?

### ISSUE THREAD

**Issue by justinwoo** [purescript/purescript-typelevel-prelude#13]
Is there a reason why we don't have a RLProxy or something in the repo? At least, it would let me work with them directly rather than to pass around Records and have to provide constraints to identify the rows from the list and the other way around.

**Comment by LiamGoodacre** [comment]
Good question.  So I didn't include one originally in anticipation of the new proxy syntax (https://github.com/purescript/purescript/pull/2846).  This will mean we can basically delete all custom proxy data types.

However, it is probably useful adding one in the mean time.  What do you think @paf31?

**Comment by paf31** [comment]
I guess it doesn't hurt to add one, since it'll be a breaking change to remove the others anyway.

**Comment by justinwoo** [comment]
Fixed by ^
