### ISSUE TITLE
Feature Request: RowCompose

### ISSUE THREAD

**Issue by eric-corumdigital** [purescript/purescript-typelevel-prelude#42]
`type RowCompose (r :: # Type -> # Type) (s :: # Type -> # Type) (a :: # Type) = r (s a)`

Can have variants for right-to-left and left-to-right, as well as operator names. I found this to have utility where RowApply is insufficient. Specifically when I need a `# Type -> # Type` and not a `# Type`.

**Comment by JordanMartinez** [comment]
This was added in #63 via the [`APPLY`/`$` type](https://github.com/purescript/purescript-typelevel-prelude/blob/v6.0.0/src/Type/Function.purs#L9-L10). It's polymorphic, so it works on rows and other types, too.
