### ISSUE TITLE
need major version increment after recent change removing export of Type.Row

### ISSUE THREAD

**Issue by rgrover** [purescript/purescript-typelevel-prelude#46]
Packages depending on typelevel-prelude and importing Type.Row could now be broken after recent changes.

Here's how purescript-record fails to build:
```
Error 1 of 5:

  in module Record
  at src/Record.purs:22:31 - 22:41 (line 22, column 31 - line 22, column 41)

    Cannot import type class Cons from module Type.Row
    It either does not exist or the module does not export it.
```

**Comment by hdgarrood** [comment]
Thanks for the heads up. I'll revert the change and release a v4.0.2, and then we'll have to release a v5.0.0 with changes necessary for the upcoming v0.13.0 compiler release.

**Comment by joneshf** [comment]
Huh, that's weird. Why did it fail [differently][] within this package? In any case, sorry about messing things up.

[differently]: https://github.com/purescript/purescript-typelevel-prelude/issues/43#issuecomment-496011963

**Comment by hdgarrood** [comment]
No worries, these things happen and everything's fine now :) No idea why it failed differently for you; I haven't been able to reproduce what you saw locally :man_shrugging:

**Comment by rgrover** [comment]
thanks a lot
