### ISSUE TITLE
Exports of Ordering and Boolean Kinds Missing

### ISSUE THREAD

**Issue by eric-corumdigital** [purescript/purescript-typelevel-prelude#55]
Dependent libraries were relying on the kind exports of Ordering and Boolean and those were removed between 5.0.0 and 5.0.1

https://github.com/purescript/purescript-typelevel-prelude/commit/dd703bac30e9cd837dba64fce4d0ff750da965d0

**Comment by hdgarrood** [comment]
Thanks for the report. There was a compiler bug which caused an unused import warning to be emitted where none should have been, which is what led to these things being removed and published as a patch level change. The compiler bug is now fixed but I guess I forgot to come back and revert the change here.

**Comment by hdgarrood** [comment]
Published as v5.0.2.
