### ISSUE TITLE
Add `#` operator to the `Type.Function`

### ISSUE THREAD

**Issue by paluh** [purescript/purescript-typelevel-prelude#70]
I think that this operator can be useful. For example it is already defined (but named differently) in the context of `React.Basic.Hooks`:

https://github.com/spicydonuts/purescript-react-basic-hooks/blob/fde4198f55bbf2b6d95ecd7d0614510b9089658b/src/React/Basic/Hooks/Internal.purs#L188

Could you please tell me what do you think? Should I provide this simple PR?

**Comment by JordanMartinez** [comment]
Please do not add it. `#` still refers to `Row`. We'll deprecate that in
the next breaking changes and then can add uh. That's why I didn't do that
in the PR.

**Comment by paluh** [comment]
Thanks for quick response Jordan! I'm going to close this then.
